package chipyard.example

// Generated by scripts/generate_auto_links.py. Do not edit.
object AutoLinksGenerated {
  val links: Seq[AutoLinkSpec] = Seq(
    AutoLinkSpec(source = "gemmini", destination = "cgra"))
}
