package chipyard.example

// Generated by scripts/generate_cgra_spm_control.py. Do not edit.
object CgraSpmControlGenerated {
  val baseAddress: BigInt = BigInt("60010000", 16)
  val pageSizeBytes: Int = 4096
  val JOB_ID: Int = 0x000
  val SLOT: Int = 0x008
  val BYTES: Int = 0x010
  val MODE: Int = 0x018
  val SPM_WORD_ADDRESS: Int = 0x020
  val DMA_TAG: Int = 0x028
  val PACKET_COUNT: Int = 0x030
  val HEADER_SUBMIT: Int = 0x038
  val PACKET_LO: Int = 0x040
  val PACKET_MID: Int = 0x048
  val PACKET_HI: Int = 0x050
  val PACKET_TOP: Int = 0x058
  val PACKET_SUBMIT: Int = 0x060
  val JOB_SUBMIT: Int = 0x068
  val STEP_SUBMIT: Int = 0x070
  val RESULT_VALID: Int = 0x080
  val RESULT_POP: Int = 0x088
  val RESULT_JOB_ID: Int = 0x090
  val RESULT_SLOT: Int = 0x098
  val RESULT_BYTES: Int = 0x0a0
  val RESULT_STAGE: Int = 0x0a8
  val RESULT_STATUS: Int = 0x0b0
  val RESULT_DETAIL: Int = 0x0b8
  val RESULT_DATA: Int = 0x0c0
}
