package chipyard.example

// Auto-generated by scripts/sync_cgra_blackbox.py from CgraRTL_2x2.
// Do not edit by hand; regenerate after PyMTL3 RTL changes.
object CGRAGenerated {
  val params = CGRAParams(
    intraPktWidth = 182,
    interPktWidth = 185,
    dataPayloadWidth = 32,
    dataWidth = 35,
    payloadWidth = 157,
    idWidth = 2,
    addrWidth = 7,
    xTiles = 2,
    yTiles = 2,
    cmdWidth = 5,
    numTiles = 4,
    addressLower = 0,
    addressUpper = 31,
    topModuleName = "CgraRTL_2x2",
    wrapperModuleName = "CgraRTL_2x2_wrapper",
    rtlResource = "/vsrc/CgraRTL_2x2__pickled.v",
    wrapperResource = "/vsrc/CgraRTL_2x2_wrapper.v"
  )
}
