package chipyard.example

// Auto-generated by scripts/sync_cgra_blackbox.py from CgraTemplateRTL_single.
// Do not edit by hand; regenerate after PyMTL3 RTL changes.
object CGRAGenerated {
  val params = CGRAParams(
    intraPktWidth = 191,
    interPktWidth = 195,
    dataPayloadWidth = 32,
    dataWidth = 35,
    payloadWidth = 162,
    idWidth = 2,
    addrWidth = 7,
    xTiles = 4,
    yTiles = 4,
    cmdWidth = 6,
    numTiles = 16,
    addressLower = 0,
    addressUpper = 31,
    hasBoundaryPorts = false,
    topModuleName = "CgraTemplateRTL_single",
    wrapperModuleName = "CgraTemplateRTL_single_wrapper",
    rtlResource = "/vsrc/CgraTemplateRTL_single__pickled.v",
    wrapperResource = "/vsrc/CgraTemplateRTL_single_wrapper.v"
  )
}
