package chipyard.example

// Generated by scripts/generate_cgra_spm_control.py. Do not edit.
object CgraSpmControlGenerated {
  val baseAddress: BigInt = BigInt("60010000", 16)
  val pageSizeBytes: Int = 4096
  val SPM_WORD_ADDRESS: Int = 0x000
  val DMA_TAG: Int = 0x008
  val PACKET_COUNT: Int = 0x010
  val CONFIG_SUBMIT: Int = 0x018
  val RESULT_VALID: Int = 0x020
  val RESULT_POP: Int = 0x028
  val RESULT_STATUS: Int = 0x030
  val RESULT_DETAIL: Int = 0x038
  val RESULT_DATA: Int = 0x040
}
