package chipyard.example

// Generated by scripts/generate_gemmini_ext_spm.py. Do not edit.
object GemminiExternalSpmGenerated {
  val baseAddress: BigInt = BigInt("60000000", 16)
  val sizeBytes: Int = 65536
}
