package chipyard.example

// Auto-generated by scripts/generate_gemmini_external_spad.py from configs/soc/cgra_soc.yaml.
// This is an intentional versioned hardware/software interface; do not edit by hand.
object GemminiExternalSpadGenerated {
  val baseAddress: BigInt = BigInt("60000000", 16)
  val sizeBytes: Int = 65536
  val spadRowBytes: Int = 16
  val fullWidthRowStride: Int = 4
  val fullWidthRowBytes: Int = 64
  val matrixDimension: Int = 16
  val outputSlotCount: Int = 2
  val outputSlotSizeBytes: Int = 1024
  val outputReservedBytes: Int = 2048
  val outputReservedBase: BigInt = BigInt("6000f800", 16)
  val outputSlotBases: Seq[BigInt] = Seq(BigInt("6000f800", 16), BigInt("6000fc00", 16))
  val outputSlotRows: Seq[Int] = Seq(3968, 4032)

  require(sizeBytes > 0 && (sizeBytes & (sizeBytes - 1)) == 0)
  require((baseAddress & (sizeBytes - 1)) == 0)
  require(outputReservedBytes == outputSlotCount * outputSlotSizeBytes)
  require(outputReservedBase == baseAddress + sizeBytes - outputReservedBytes)
  require(outputSlotBases.size == outputSlotCount)
  require(outputSlotRows.size == outputSlotCount)
  require(outputSlotBases.zipWithIndex.forall { case (address, index) =>
    address == outputReservedBase + index * outputSlotSizeBytes
  })
  require(outputSlotRows.zip(outputSlotBases).forall { case (row, address) =>
    baseAddress + row * spadRowBytes == address
  })
}
