package chipyard.example

// Auto-generated by scripts/openfpga/chipyard.py.
case class OpenFPGAUserField(name: String, width: Int, lsb: Int)

object OpenFPGAGenerated {
  val Name = "openfpga_and2"
  val ApplicationName = "and2"
  val ConfigName = "OpenFPGADemoRocketConfig"
  val PeripheralName = "openfpga_and2"
  val Compatible = "ucbbar,openfpga-and2"
  val WrapperModule = "OpenFPGAAnd2Wrapper"
  val WrapperPath = "/home/jjqin/CGRA-SoC/chipyard/generators/chipyard/src/main/resources/vsrc/openfpga_and2/OpenFPGAAnd2Wrapper.v"

  val BaseAddress = BigInt("10050000", 16)
  val Size = BigInt("1000", 16)

  val BitstreamLength = 1502
  val CfgWordWidth = 15
  val CfgAddrWidth = 14
  val CfgDataWidth = 1

  val InputRegisterName = "USER_INPUT"
  val InputWidth = 2
  val InputFields = Seq(OpenFPGAUserField("a", 1, 0), OpenFPGAUserField("b", 1, 1))

  val OutputRegisterName = "USER_OUTPUT"
  val OutputWidth = 1
  val OutputFields = Seq(OpenFPGAUserField("c", 1, 0))
}
