package chipyard.example

// Generated by scripts/generate_shared_spm.py. Do not edit.
object SharedSpmGenerated {
  val baseAddress: BigInt = BigInt("60000000", 16)
  val sizeBytes: Int = 65536
  val slotCount: Int = 2
  val slotSizeBytes: Int = 1024
  val slotBase: BigInt = BigInt("6000f800", 16)
  val slotBases: Seq[BigInt] = Seq(BigInt("6000f800", 16), BigInt("6000fc00", 16))
}
