package chipyard.example

// Generated by scripts/generate_spm_links.py. Do not edit.
object SpmLinksGenerated {
  val links: Seq[SpmLinkSpec] = Seq(
    SpmLinkSpec(source = "gemmini", destination = "cgra"))
}
