//-------------------------------------------------------------------------
// CgraTemplateRTL_single_wrapper.v
//-------------------------------------------------------------------------
// Auto-generated by scripts/sync_cgra_blackbox.py.
// Wraps PyMTL3-generated CgraTemplateRTL_single and flattens struct/array ports
// for Chisel BlackBox compatibility.
//-------------------------------------------------------------------------

module CgraTemplateRTL_single_wrapper (
  input  logic        clk,
  input  logic        reset,
  input  logic        recv_from_cpu_pkt_val,
  input  logic [209:0] recv_from_cpu_pkt_msg,
  output logic        recv_from_cpu_pkt_rdy,
  output logic        send_to_cpu_pkt_val,
  output logic [209:0] send_to_cpu_pkt_msg,
  input  logic        send_to_cpu_pkt_rdy,
  input  logic        recv_from_inter_cgra_noc_val,
  input  logic [212:0] recv_from_inter_cgra_noc_msg,
  output logic        recv_from_inter_cgra_noc_rdy,
  output logic        send_to_inter_cgra_noc_val,
  output logic [212:0] send_to_inter_cgra_noc_msg,
  input  logic        send_to_inter_cgra_noc_rdy,
  input  logic cgra_id,
  input  logic [6:0] address_lower,
  input  logic [6:0] address_upper
);

  IntraCgraPacket_1_1x1_4_8_2_CgraPayload__307a0bf83590d46b w_recv_from_cpu_pkt_msg;
  IntraCgraPacket_1_1x1_4_8_2_CgraPayload__307a0bf83590d46b w_send_to_cpu_pkt_msg;
  InterCgraPacket_1_1x1_4_8_4_CgraPayload__7b72a6a48303ce93 w_recv_from_inter_cgra_noc_msg;
  InterCgraPacket_1_1x1_4_8_4_CgraPayload__7b72a6a48303ce93 w_send_to_inter_cgra_noc_msg;


  assign w_recv_from_cpu_pkt_msg = recv_from_cpu_pkt_msg;
  assign send_to_cpu_pkt_msg = w_send_to_cpu_pkt_msg;
  assign w_recv_from_inter_cgra_noc_msg = recv_from_inter_cgra_noc_msg;
  assign send_to_inter_cgra_noc_msg = w_send_to_inter_cgra_noc_msg;



  CgraTemplateRTL_single cgra_inst (
    .clk                                ( clk ),
    .reset                              ( reset ),
    .recv_from_cpu_pkt__val             ( recv_from_cpu_pkt_val ),
    .recv_from_cpu_pkt__msg             ( w_recv_from_cpu_pkt_msg ),
    .recv_from_cpu_pkt__rdy             ( recv_from_cpu_pkt_rdy ),
    .send_to_cpu_pkt__val               ( send_to_cpu_pkt_val ),
    .send_to_cpu_pkt__msg               ( w_send_to_cpu_pkt_msg ),
    .send_to_cpu_pkt__rdy               ( send_to_cpu_pkt_rdy ),
    .recv_from_inter_cgra_noc__val      ( recv_from_inter_cgra_noc_val ),
    .recv_from_inter_cgra_noc__msg      ( w_recv_from_inter_cgra_noc_msg ),
    .recv_from_inter_cgra_noc__rdy      ( recv_from_inter_cgra_noc_rdy ),
    .send_to_inter_cgra_noc__val        ( send_to_inter_cgra_noc_val ),
    .send_to_inter_cgra_noc__msg        ( w_send_to_inter_cgra_noc_msg ),
    .send_to_inter_cgra_noc__rdy        ( send_to_inter_cgra_noc_rdy ),
    .cgra_id                            ( cgra_id ),
    .address_lower                      ( address_lower ),
    .address_upper                      ( address_upper )
  );

endmodule
