package chipyard

import org.chipsalliance.cde.config.Config

// Auto-generated by scripts/openfpga/chipyard.py.
class OpenFPGAGcd6K4FrameRocketConfig extends Config(
  new chipyard.example.WithOpenFPGADemo() ++
  new freechips.rocketchip.rocket.WithNHugeCores(1) ++
  new chipyard.config.AbstractConfig)
